#ifndef _SDS7102_KEYS_H
#define _SDS7102_KEYS_H

#define SDS_KEY_F1		KEY_F1
#define SDS_KEY_F2		KEY_F2
#define SDS_KEY_F3		KEY_F3
#define SDS_KEY_F4		KEY_F4
#define SDS_KEY_F5		KEY_F5

#define SDS_KEY_H1		KEY_F6
#define SDS_KEY_H2		KEY_F7
#define SDS_KEY_H3		KEY_F8
#define SDS_KEY_H4		KEY_F9
#define SDS_KEY_H5		KEY_F10

#define SDS_KEY_MENU_OFF	KEY_ESC

#define SDS_KEY_COPY		KEY_COPY

#define SDS_KEY_MEASURE		KEY_F11
#define SDS_KEY_ACQUIRE		KEY_F12
#define SDS_KEY_AUTOSET		KEY_F13
#define SDS_KEY_UTILITY		KEY_F14
#define SDS_KEY_CURSOR		KEY_F15
#define SDS_KEY_AUTOSCALE	KEY_F16
#define SDS_KEY_SAVE		KEY_SAVE
#define SDS_KEY_DISPLAY		KEY_F17
#define SDS_KEY_HELP		KEY_HELP

#define SDS_KEY_RUN_STOP	KEY_PLAY
#define SDS_KEY_SINGLE		KEY_PAUSE

#define SDS_KEY_MATH_MENU	KEY_F18
#define SDS_KEY_CH1_MENU	KEY_F19
#define SDS_KEY_CH2_MENU	KEY_F20
#define SDS_KEY_HORIZ_MENU	KEY_F21

#define SDS_KEY_TRIG_MENU	KEY_F22
#define SDS_KEY_TRIG_50		KEY_F23
#define SDS_KEY_TRIG_FORCE	KEY_F24

#define SDS_KEY_CH1_POS		BTN_X
#define SDS_REL_CH1_POS		REL_X
#define SDS_KEY_CH1_SCALE	BTN_A
#define SDS_REL_CH1_SCALE	REL_RX

#define SDS_KEY_CH2_POS		BTN_Y
#define SDS_REL_CH2_POS		REL_Y
#define SDS_KEY_CH2_SCALE	BTN_B
#define SDS_REL_CH2_SCALE	REL_RY

#define SDS_KEY_HORIZ_POS	BTN_Z
#define SDS_REL_HORIZ_POS	REL_Z
#define SDS_KEY_HORIZ_SCALE	BTN_C
#define SDS_REL_HORIZ_SCALE	REL_RZ

#define SDS_KEY_TRIG		BTN_TL
#define SDS_REL_TRIG		REL_WHEEL
#define SDS_KEY_MULTI		BTN_TR
#define SDS_REL_MULTI		REL_DIAL

#endif /* _SDS7102_KEYS_H */
